"""init

Revision ID: 2fcfa617fdf1
Revises: 
Create Date: 2023-06-03 19:47:45.238442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fcfa617fdf1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('num', sa.Integer(), nullable=True),
    sa.Column('first_name', sa.TEXT(), nullable=True),
    sa.Column('second_name', sa.TEXT(), nullable=True),
    sa.Column('third_name', sa.TEXT(), nullable=True),
    sa.Column('password', sa.TEXT(), nullable=True),
    sa.Column('type', sa.Enum('admin', 'regular_user', name='usertypes'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('num')
    )
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('receipt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('component',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('receipt_id', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Double(), nullable=True),
    sa.Column('status', sa.Enum('active', 'inactive', name='componentstatuses'), nullable=True),
    sa.Column('activation_date', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['receipt_id'], ['receipt.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('load',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('receipt_id', sa.Integer(), nullable=True),
    sa.Column('out_weight', sa.Integer(), nullable=True),
    sa.Column('date', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['receipt_id'], ['receipt.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('load')
    op.drop_table('component')
    op.drop_table('receipt')
    op.drop_table('product')
    op.drop_table('client')
    # ### end Alembic commands ###
