"""spasite

Revision ID: 31d62450114c
Revises: a033a723ddd7
Create Date: 2023-06-04 17:27:20.403916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31d62450114c'
down_revision = 'a033a723ddd7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('param', sa.Column('status', sa.Enum('active', 'inactive', name='componentstatuses'), nullable=True))
    op.add_column('param', sa.Column('activation_date', sa.TIMESTAMP(), nullable=True))
    op.add_column('task', sa.Column('value', sa.TEXT(), nullable=True))
    op.add_column('task', sa.Column('done_time', sa.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'done_time')
    op.drop_column('task', 'value')
    op.drop_column('param', 'activation_date')
    op.drop_column('param', 'status')
    # ### end Alembic commands ###
