"""add out weight for receipt

Revision ID: ad38cf47e584
Revises: 0c34738c722f
Create Date: 2023-06-05 07:41:13.301566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad38cf47e584'
down_revision = '0c34738c722f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('receipt', sa.Column('out_weight', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('receipt', 'out_weight')
    # ### end Alembic commands ###
